### ISSUE TITLE
Downloads don't start!

### ISSUE THREAD

**Issue by giannoxs** [LeoniePhiline/showcase-dl#17]
Hi @LeoniePhiline @joshka , I am trying your tool to download the showcase from Vimeo, I write the command  showcase-dl URL, like https://vimeo.com/showcase/9625437, and I see already the written "Finished" at the top and not any of the downloads. What's wrong? Do I miss something to make it work in the right way?

![Screenshot](https://github.com/LeoniePhiline/showcase-dl/assets/142550790/f8bd533a-dc9e-4638-9713-826e09d34e9b)

**Comment by joshka** [comment]
Hey there - just a quick etiquette thing. There's no need to tag people in a PR most of the time, as the PR will notify the owners automatically. I don't actually know much about this app at all, so I'll leave that to Leonie to address.

Also I noticed that you wrote this comment twice - here and in Issue #16 (perhaps delete the other comment if it's unrelated to the issue).

**Comment by giannoxs** [comment]
Yeah,thanks for the advice, sorry for the mistake. Could you ask this to Leonie too with a private message? I need to download these videos as soon as possible. Thanks in advance.

**Comment by giannoxs** [comment]
LOG DEBUG

 [2m2023-08-19T11:53:32.988420Z[0m [34mDEBUG[0m [1;34mshowcase_dl[0m[34m: [34mParsed page URL: Url {
    scheme: "https",
    cannot_be_a_base: false,
    username: "",
    password: None,
    host: Some(
        Domain(
            "vimeo.com",
        ),
    ),
    port: None,
    path: "/showcase/10325458",
    query: None,
    fragment: None,
}[0m
    [2;3mat[0m src\main.rs:75 [2;3mon[0m main

  [2m2023-08-19T11:53:32.988476Z[0m [32m INFO[0m [1;32mshowcase_dl[0m[32m: [32mFetch source page...[0m
    [2;3mat[0m src\main.rs:83 [2;3mon[0m main

  [2m2023-08-19T11:53:32.988812Z[0m [34mDEBUG[0m [1;34mreqwest::connect[0m[34m: [34mstarting new connection: https://vimeo.com/[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\reqwest-0.11.18\src\connect.rs:429 [2;3mon[0m main

  [2m2023-08-19T11:53:32.989108Z[0m [34mDEBUG[0m [1;34mhyper::client::connect::dns[0m[34m: [34mresolving host="vimeo.com"[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\client\connect\dns.rs:122 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:32.998883Z[0m [34mDEBUG[0m [1;34mhyper::client::connect::http[0m[34m: [34mconnecting to 162.159.138.60:443[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\client\connect\http.rs:537 [2;3mon[0m main

  [2m2023-08-19T11:53:33.011664Z[0m [34mDEBUG[0m [1;34mhyper::client::connect::http[0m[34m: [34mconnected to 162.159.138.60:443[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\client\connect\http.rs:540 [2;3mon[0m main

  [2m2023-08-19T11:53:33.011730Z[0m [34mDEBUG[0m [1;34mrustls::client::hs[0m[34m: [34mNo cached session for DnsName("vimeo.com")[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.21.3\src\client\hs.rs:73 [2;3mon[0m main

  [2m2023-08-19T11:53:33.011826Z[0m [34mDEBUG[0m [1;34mrustls::client::hs[0m[34m: [34mNot resuming any session[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.21.3\src\client\hs.rs:132 [2;3mon[0m main

  [2m2023-08-19T11:53:33.023916Z[0m [34mDEBUG[0m [1;34mrustls::client::hs[0m[34m: [34mUsing ciphersuite TLS13_AES_256_GCM_SHA384[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.21.3\src\client\hs.rs:615 [2;3mon[0m main

  [2m2023-08-19T11:53:33.025236Z[0m [34mDEBUG[0m [1;34mrustls::client::tls13[0m[34m: [34mNot resuming[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.21.3\src\client\tls13.rs:142 [2;3mon[0m main

  [2m2023-08-19T11:53:33.025462Z[0m [34mDEBUG[0m [1;34mrustls::client::tls13[0m[34m: [34mTLS1.3 encrypted extensions: [ServerNameAck, Protocols([ProtocolName(687474702f312e31)])][0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.21.3\src\client\tls13.rs:381 [2;3mon[0m main

  [2m2023-08-19T11:53:33.025494Z[0m [34mDEBUG[0m [1;34mrustls::client::hs[0m[34m: [34mALPN protocol is Some(b"http/1.1")[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.21.3\src\client\hs.rs:472 [2;3mon[0m main

  [2m2023-08-19T11:53:33.026624Z[0m [34mDEBUG[0m [1;34mhyper::proto::h1::io[0m[34m: [34mflushed 65 bytes[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\proto\h1\io.rs:342 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.241533Z[0m [34mDEBUG[0m [1;34mhyper::proto::h1::io[0m[34m: [34mparsed 28 headers[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\proto\h1\io.rs:207 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.241591Z[0m [34mDEBUG[0m [1;34mhyper::proto::h1::conn[0m[34m: [34mincoming body is chunked encoding[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\proto\h1\conn.rs:222 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.241883Z[0m [34mDEBUG[0m [1;34mhyper::proto::h1::decode[0m[34m: [34mincoming chunked header: 0x7AA5 (31397 bytes)[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\proto\h1\decode.rs:298 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.248244Z[0m [34mDEBUG[0m [1;34mhyper::proto::h1::decode[0m[34m: [34mincoming chunked header: 0x8000 (32768 bytes)[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\proto\h1\decode.rs:298 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.255020Z[0m [34mDEBUG[0m [1;34mhyper::proto::h1::decode[0m[34m: [34mincoming chunked header: 0x6C8F (27791 bytes)[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\proto\h1\decode.rs:298 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.259829Z[0m [34mDEBUG[0m [1;34mhyper::proto::h1::conn[0m[34m: [34mincoming body completed[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\proto\h1\conn.rs:298 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.259909Z[0m [34mDEBUG[0m [1;34mhyper::client::pool[0m[34m: [34mpooling idle connection for ("https", vimeo.com)[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\client\pool.rs:376 [2;3mon[0m tokio-runtime-worker

  [2m2023-08-19T11:53:33.260170Z[0m [32m INFO[0m [1;32mshowcase_dl[0m[32m: [32mExtract vimeo embeds...[0m
    [2;3mat[0m src\main.rs:89 [2;3mon[0m main

  [2m2023-08-19T11:53:33.260258Z[0m [34mDEBUG[0m [1;34mrustls::common_state[0m[34m: [34mSending warning alert CloseNotify[0m
    [2;3mat[0m C:\Users\WDAGUtilityAccount\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.21.3\src\common_state.rs:498 [2;3mon[0m tokio-runtime-worker

**Comment by giannoxs** [comment]
[showcase-dl.log](https://github.com/LeoniePhiline/showcase-dl/files/12385781/showcase-dl.log)

**Comment by giannoxs** [comment]
I have tried to use it on Linux too, and it doesn't work as well, What do I do wrong? Someone knows?

**Comment by LeoniePhiline** [comment]
@giannoxs The tool was built to download showcases which are embedded on some webpage. However, I wanted to support your case (providing a showcase link directly) as well.

Currently, your showcases (https://vimeo.com/showcase/10325458 / https://vimeo.com/showcase/9625437) are set to "private". 
Do you have a working showcase link?

**Comment by giannoxs** [comment]
@LeoniePhiline No, so I can't do it.

**Comment by giannoxs** [comment]
@LeoniePhiline No, so it is not possible to download it.

**Comment by giannoxs** [comment]
@LeoniePhiline No, so it is not possible to download it.
What can I do?

**Comment by LeoniePhiline** [comment]
What do you mean? Do you have the password? Was it not set to private previously?
If you have no access to the showcases, then you cannot archive them.

On a side note: There is no need to mention me. I get notified about every comment, anyway.
