### ISSUE TITLE
Suggestions and questions for `showcase-dl --help`

### ISSUE THREAD

**Issue by kiri35** [LeoniePhiline/showcase-dl#23]
Here are a few suggestions and questions for `showcase-dl --help`:
~~~
Arguments:
…
old:  <URL>                      URL - Either the target page, containing Vimeo showcase embeds, or a Vimeo showcase URL (with --referer)
new:  <URL>                      URL - Either the target page, containing Vimeo [showcase] URLs embeds, or a single such URL (with or without --referer)

Options:
old:  -v, --verbose...           More output per occurrence
new:  -v,-vv,-vvv, --verbose...  More, even more output per occurrence, debug-level log verbosity
~~~
question 1: What is the meaning of "..."?
question 2: What are the long options for -vv and -vvv? Is it the following?:
~~~
  -v,-vv,-vvv, --verbose,--verboseverbose,--verboseverboseverbose  More, even more output per occurrence, debug-level log verbosity
~~~
question 3: What is the meaning of "..." in?:
~~~
  -q, --quiet...                 Less output per occurrence
~~~

**Comment by LeoniePhiline** [comment]
The `...` indicates that an option can be passed multiple times.

Options can have a long form, prefixed by `--`, and a short (single letter) form, prefixed by `-`.

Short (single letter) options can be grouped together (as long as they take no arguments). E.g. If there would exist the long options `--wow` and `--yeah` with their short forms `-w` and `-y`, then you could group the short forms together as `-wy` or `-yw` if you want to activate both.

This also explains `-vv`, `-vvv` etc. - these are equivalent to multiple times `--verbose`.
The same is true for `-q` (quiet) or `-qq` (very quiet, equal to `--quiet --quiet`).

This is all standard on Linux / UNIX systems.

**Comment by kiri35** [comment]
Thank you. Now i understand :-)
