### ISSUE TITLE
Password protected showcases

### ISSUE THREAD

**Issue by R3mbrandt** [LeoniePhiline/showcase-dl#91]
Hi!

Are password-protected showcases supported? If so, how can I provide the password? 

Thx!

**Comment by LeoniePhiline** [comment]
Hi!

If the showcase itself is password protected, then I’m sorry - there isn’t currently a way to provide the password.

However, if the showcase is public, but merely videos in it are password protected, then you can pass the password as part of the `yt-dlp` extra arguments after two dashes. See section [Passing options to the downloader and extracting audio](https://github.com/LeoniePhiline/showcase-dl/blob/main/README.md#passing-options-to-the-downloader-and-extracting-audio)

**Comment by LeoniePhiline** [comment]
In case you are comfortable sharing the showcase URL and password then of course please be welcome to do so. Either right here, or you can leave your matrix handle.

**Comment by R3mbrandt** [comment]
Thx for your reply! I've found out that yt-dlp (https://github.com/yt-dlp/yt-dlp) support download of password protected vimeo showcases by providing the password via the "video-password" option.

**Comment by LeoniePhiline** [comment]
`yt-dlp` supports showcases by now? Thank you for letting me know! This means it is time to archive this repository.

**Comment by jonnyijapan** [comment]
Last time I tried (yesterday), yt-dlp could not download a showcase. But then again the showcase I tried it on needs a password, so maybe neither yt-dlp nor showcase-dl can handle this case as of now?

**Comment by LeoniePhiline** [comment]
> But then again the showcase I tried it on needs a password, so maybe neither yt-dlp nor showcase-dl can handle this case as of now?

Yes, indeed. If passing `-- --video-password <password>` or `-- -u <username> -p <password>` as [additional arguments](https://github.com/LeoniePhiline/showcase-dl/blob/main/README.md#passing-options-to-the-downloader-and-extracting-audio) does not help, then there is currently no way.

I would need a password protected example showcase (and the corresponding password) to figure out how the service asks for the password and how we can provide it.
